# Docker Compose for DC EPUB Composer
# Runs both the API server and background worker

version: '3.8'

services:
  epub-composer-api:
    build: .
    container_name: dc-epub-composer-api
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DEBUG=false
      - STORAGE_ROOT=/app/storage
      - PYTHONPATH=/app
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks:
      - dc-network
    restart: unless-stopped
    depends_on:
      - epub-composer-worker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  epub-composer-worker:
    build: .
    container_name: dc-epub-composer-worker
    command: ["python", "main.py"]
    environment:
      - STORAGE_ROOT=/app/storage
      - SLEEP_INTERVAL=10
      - DEFAULT_COMPOSER=simple_markdown
      - PYTHONPATH=/app
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks:
      - dc-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/storage') else 1)"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  storage:
    driver: local
  logs:
    driver: local

networks:
  dc-network:
    driver: bridge